// The NB Classic Scents catalogue. Image paths point at studio renders of each
// bottle (generated from the same procedural 3D model the storefront uses).

const img = (slug) => [`/uploads/products/${slug}-1.webp`, `/uploads/products/${slug}-2.webp`, `/uploads/products/${slug}-3.webp`];

const sizes = (p30, p50, p100, stock = [18, 24, 12]) => [
  { size: '30 ml', price: p30, stock: stock[0] },
  { size: '50 ml', price: p50, stock: stock[1] },
  { size: '100 ml', price: p100, stock: stock[2] },
];

const categories = [
  { name: "Women's", slug: 'women', kind: 'audience', order: 1, description: 'Luminous florals and soft, sensual musks.' },
  { name: "Men's", slug: 'men', kind: 'audience', order: 2, description: 'Woods, spice and quiet confidence.' },
  { name: 'Unisex', slug: 'unisex', kind: 'audience', order: 3, description: 'Compositions that belong to whoever wears them.' },
  { name: 'Oud Collection', slug: 'oud', kind: 'collection', order: 1, description: 'Rare agarwood, resins and smoke, composed with restraint.' },
  { name: 'Signature Collection', slug: 'signature', kind: 'collection', order: 2, description: 'The three founding scents of the house.' },
  { name: 'Limited Edition', slug: 'limited-edition', kind: 'collection', order: 3, description: 'Small-batch creations, released once.' },
  { name: 'Gift Sets', slug: 'gift-sets', kind: 'collection', order: 4, description: 'Coffrets composed for giving.' },
];

const products = [
  {
    name: 'Éclat',
    slug: 'eclat',
    tagline: 'Bergamot · Jasmine · White Musk',
    gender: 'women',
    cats: ['women', 'signature'],
    fragranceFamily: 'Floral Musk',
    description:
      'Éclat is the first light of morning caught in glass. Sparkling Calabrian bergamot opens onto a heart of sun-warmed jasmine sambac, settling into a veil of white musk that stays close to the skin like a second silk.',
    story: 'Composed as the opening signature of the house, Éclat was built around a single idea: radiance without noise.',
    notes: { top: ['Bergamot', 'Pink Pepper', 'Mandarin'], heart: ['Jasmine Sambac', 'Orange Blossom', 'Iris'], base: ['White Musk', 'Cashmeran', 'Blonde Woods'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Limonene, Linalool, Benzyl Salicylate, Hydroxycitronellal, Citral, Geraniol.',
    longevity: '8 – 10 hours',
    sillage: 'Moderate',
    variants: sizes(9500, 14500, 22500, [20, 26, 14]),
    bottle: { shape: 'classic', liquid: '#EBDDB4', cap: 'gold', glass: 'clear' },
    featured: true,
    signatureOrder: 1,
    bestseller: true,
  },
  {
    name: 'Essence',
    slug: 'essence',
    tagline: 'Rose · Vanilla · Amber',
    gender: 'women',
    cats: ['women', 'signature'],
    fragranceFamily: 'Amber Floral',
    description:
      'A portrait of the Damask rose at dusk. Essence wraps velvet petals in Madagascan vanilla and a glowing amber accord — warm, intimate and unmistakably feminine.',
    story: 'Essence was created for evenings that are remembered long after they end.',
    notes: { top: ['Lychee', 'Pink Pepper', 'Bergamot'], heart: ['Damask Rose', 'Peony', 'Jasmine'], base: ['Bourbon Vanilla', 'Amber', 'Benzoin'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Citronellol, Geraniol, Linalool, Coumarin, Eugenol, Benzyl Benzoate.',
    longevity: '9 – 11 hours',
    sillage: 'Moderate to strong',
    variants: sizes(9800, 14900, 23500, [16, 22, 10]),
    bottle: { shape: 'round', liquid: '#E3B98E', cap: 'gold', glass: 'clear' },
    featured: true,
    signatureOrder: 2,
    bestseller: true,
  },
  {
    name: 'Noir',
    slug: 'noir',
    tagline: 'Oud · Sandalwood · Tonka',
    gender: 'men',
    cats: ['men', 'signature', 'oud'],
    fragranceFamily: 'Woody Oriental',
    description:
      'Noir is quiet power. Smoked Cambodian oud and creamy Mysore-style sandalwood are softened by roasted tonka bean — a deep, polished trail that commands the room without raising its voice.',
    story: 'The darkest of the signatures, Noir is bottled in smoked glass to protect its precious oud accord.',
    notes: { top: ['Cardamom', 'Saffron', 'Black Pepper'], heart: ['Oud', 'Leather', 'Cypriol'], base: ['Sandalwood', 'Tonka Bean', 'Vetiver'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Coumarin, Linalool, Limonene, Isoeugenol, Eugenol.',
    longevity: '10 – 12 hours',
    sillage: 'Strong',
    variants: sizes(11500, 17500, 27500, [14, 18, 9]),
    bottle: { shape: 'facet', liquid: '#5B3A1E', cap: 'black', glass: 'smoke' },
    featured: true,
    signatureOrder: 3,
    bestseller: true,
  },
  {
    name: 'Soie',
    slug: 'soie',
    tagline: 'Iris · Pear · Cashmere Musk',
    gender: 'women',
    cats: ['women'],
    fragranceFamily: 'Powdery Floral',
    description: 'As soft as silk against the wrist. Juicy pear gives way to buttery orris root and a cloud of cashmere musk — polished, powdery and endlessly wearable.',
    notes: { top: ['Pear', 'Bergamot'], heart: ['Iris', 'Violet Leaf', 'Heliotrope'], base: ['Cashmere Musk', 'Ambrette', 'Cedarwood'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Alpha-Isomethyl Ionone, Linalool, Limonene, Coumarin.',
    longevity: '7 – 9 hours',
    sillage: 'Intimate',
    variants: sizes(8900, 13500, 20500),
    bottle: { shape: 'tall', liquid: '#EFE3D0', cap: 'ivory', glass: 'clear' },
    isNewArrival: true,
  },
  {
    name: 'Aurum',
    slug: 'aurum',
    tagline: 'Saffron · Oud · Golden Amber',
    gender: 'unisex',
    cats: ['unisex', 'oud'],
    fragranceFamily: 'Amber Woody',
    description: 'Liquid gold. Precious saffron threads glow over a heart of rose-tinted oud, finished with a resinous golden amber that radiates warmth for hours.',
    notes: { top: ['Saffron', 'Bergamot', 'Elemi'], heart: ['Oud', 'Turkish Rose', 'Davana'], base: ['Golden Amber', 'Labdanum', 'Musk'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Citronellol, Geraniol, Linalool, Eugenol, Farnesol.',
    longevity: '10 – 12 hours',
    sillage: 'Strong',
    variants: sizes(12500, 18900, 29500, [10, 14, 6]),
    bottle: { shape: 'flacon', liquid: '#D9A85C', cap: 'gold', glass: 'clear' },
    bestseller: true,
  },
  {
    name: 'Vétiver Royal',
    slug: 'vetiver-royal',
    tagline: 'Grapefruit · Vetiver · Cedar',
    gender: 'men',
    cats: ['men'],
    fragranceFamily: 'Aromatic Woody',
    description: 'Crisp, green and impeccably tailored. Pink grapefruit and clary sage meet Haitian vetiver and Atlas cedar in a fragrance of effortless distinction.',
    notes: { top: ['Grapefruit', 'Bergamot', 'Clary Sage'], heart: ['Vetiver', 'Geranium', 'Violet Leaf'], base: ['Atlas Cedar', 'Ambroxan', 'Oakmoss'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Limonene, Linalool, Citral, Evernia Prunastri (Oakmoss) Extract.',
    longevity: '7 – 9 hours',
    sillage: 'Moderate',
    variants: sizes(8900, 13900, 21500),
    bottle: { shape: 'tall', liquid: '#D8CFA2', cap: 'black', glass: 'clear' },
  },
  {
    name: 'Blanc',
    slug: 'blanc',
    tagline: 'Neroli · Orange Blossom · Musk',
    gender: 'unisex',
    cats: ['unisex'],
    fragranceFamily: 'Citrus Floral',
    description: 'Clean linen drying in a Mediterranean breeze. Tunisian neroli and orange blossom glow over a skin-like white musk — pure, luminous, quietly addictive.',
    notes: { top: ['Neroli', 'Petitgrain', 'Lemon'], heart: ['Orange Blossom', 'Jasmine', 'Lily of the Valley'], base: ['White Musk', 'Ambrette', 'Vetiver'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Limonene, Linalool, Farnesol, Hydroxycitronellal.',
    longevity: '6 – 8 hours',
    sillage: 'Intimate',
    variants: sizes(8500, 12900, 19500),
    bottle: { shape: 'classic', liquid: '#F3EEDF', cap: 'ivory', glass: 'clear' },
    isNewArrival: true,
  },
  {
    name: 'Minuit',
    slug: 'minuit',
    tagline: 'Black Pepper · Leather · Patchouli',
    gender: 'men',
    cats: ['men'],
    fragranceFamily: 'Leather Chypre',
    description: 'The hour when the city goes quiet. Black pepper sparks over supple Italian leather and dark patchouli, drying down to a smoky, magnetic warmth.',
    notes: { top: ['Black Pepper', 'Bergamot', 'Pimento'], heart: ['Leather', 'Iris', 'Clove'], base: ['Patchouli', 'Labdanum', 'Birch Tar'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Linalool, Eugenol, Coumarin, Limonene.',
    longevity: '9 – 11 hours',
    sillage: 'Moderate to strong',
    variants: sizes(10500, 15900, 24500, [12, 3, 8]),
    bottle: { shape: 'classic', liquid: '#6B4A2E', cap: 'black', glass: 'black' },
  },
  {
    name: 'Oud Impérial',
    slug: 'oud-imperial',
    tagline: 'Rose · Oud · Incense',
    gender: 'unisex',
    cats: ['unisex', 'oud', 'limited-edition'],
    fragranceFamily: 'Oriental Woody',
    description:
      'A regal meditation. Taif rose and aged Hindi oud rise through ribbons of frankincense in a limited edition composed from our most precious reserves. Each bottle is individually numbered.',
    notes: { top: ['Saffron', 'Raspberry', 'Elemi'], heart: ['Taif Rose', 'Hindi Oud', 'Geranium'], base: ['Frankincense', 'Myrrh', 'Sandalwood'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Citronellol, Geraniol, Eugenol, Linalool.',
    longevity: '12+ hours',
    sillage: 'Strong',
    variants: [
      { size: '50 ml', price: 34500, stock: 7 },
      { size: '100 ml', price: 52000, stock: 3 },
    ],
    bottle: { shape: 'facet', liquid: '#8A4F2A', cap: 'gold', glass: 'smoke' },
    isNewArrival: true,
  },
  {
    name: "Jardin d'Ivoire",
    slug: 'jardin-divoire',
    tagline: 'Tuberose · Gardenia · Sandalwood',
    gender: 'women',
    cats: ['women'],
    fragranceFamily: 'White Floral',
    description: 'An ivory garden at midnight. Creamy tuberose and gardenia bloom over milky sandalwood — opulent, luminous and utterly romantic.',
    notes: { top: ['Green Mandarin', 'Coconut Water'], heart: ['Tuberose', 'Gardenia', 'Ylang-Ylang'], base: ['Sandalwood', 'Vanilla', 'Musk'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Benzyl Salicylate, Linalool, Farnesol, Benzyl Benzoate.',
    longevity: '8 – 10 hours',
    sillage: 'Moderate to strong',
    variants: sizes(9900, 14900, 22900),
    bottle: { shape: 'round', liquid: '#F1E6C8', cap: 'ivory', glass: 'clear' },
  },
  {
    name: 'Cèdre',
    slug: 'cedre',
    tagline: 'Cardamom · Cedarwood · Ambergris',
    gender: 'men',
    cats: ['men'],
    fragranceFamily: 'Woody Spicy',
    description: 'Mountain air and sun-warmed timber. Green cardamom lifts a heart of Virginian cedar that settles into a salty, mineral ambergris.',
    notes: { top: ['Cardamom', 'Juniper', 'Bergamot'], heart: ['Cedarwood', 'Lavender', 'Nutmeg'], base: ['Ambergris', 'Guaiac Wood', 'Musk'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Linalool, Limonene, Coumarin, Geraniol.',
    longevity: '8 – 10 hours',
    sillage: 'Moderate',
    variants: sizes(9200, 13900, 21900, [2, 15, 11]),
    bottle: { shape: 'facet', liquid: '#C9AE7A', cap: 'gold', glass: 'clear' },
  },
  {
    name: 'Lumière',
    slug: 'lumiere',
    tagline: 'Mandarin · Magnolia · Vanilla',
    gender: 'women',
    cats: ['women'],
    fragranceFamily: 'Floral Gourmand',
    description: 'Golden hour in a bottle. Sparkling mandarin and creamy magnolia melt into a soft vanilla glow — joyful, warm and radiant.',
    notes: { top: ['Mandarin', 'Pear', 'Bergamot'], heart: ['Magnolia', 'Jasmine', 'Freesia'], base: ['Vanilla', 'Praline', 'Musk'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Limonene, Linalool, Coumarin, Benzyl Alcohol.',
    longevity: '7 – 9 hours',
    sillage: 'Moderate',
    variants: sizes(8900, 13500, 20900),
    bottle: { shape: 'flacon', liquid: '#F0D9A4', cap: 'gold', glass: 'clear' },
    bestseller: true,
  },
  {
    name: 'Safran Noir',
    slug: 'safran-noir',
    tagline: 'Saffron · Oud · Leather',
    gender: 'unisex',
    cats: ['unisex', 'oud', 'limited-edition'],
    fragranceFamily: 'Leather Oud',
    description: 'A limited release of rare intensity. Persian saffron and smoked oud are bound in dark leather and castoreum-free animalic notes for a trail of absolute presence.',
    notes: { top: ['Saffron', 'Nutmeg', 'Pink Pepper'], heart: ['Oud', 'Leather', 'Rose Absolute'], base: ['Castoreum Accord', 'Styrax', 'Amber'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Eugenol, Linalool, Coumarin, Isoeugenol.',
    longevity: '12+ hours',
    sillage: 'Strong',
    variants: [
      { size: '50 ml', price: 31500, stock: 5 },
      { size: '100 ml', price: 47500, stock: 0 },
    ],
    bottle: { shape: 'classic', liquid: '#4A2A18', cap: 'gold', glass: 'black' },
    discountPercent: 0,
  },
  {
    name: 'Ambre Nuit',
    slug: 'ambre-nuit',
    tagline: 'Labdanum · Benzoin · Vanilla',
    gender: 'unisex',
    cats: ['unisex'],
    fragranceFamily: 'Amber',
    description: 'A velvet night sky of resins. Rich labdanum, Siam benzoin and smoked vanilla create a warm, enveloping amber that glows on the skin.',
    notes: { top: ['Bergamot', 'Cinnamon'], heart: ['Labdanum', 'Rose', 'Myrrh'], base: ['Benzoin', 'Vanilla', 'Tonka Bean'] },
    ingredients: 'Alcohol Denat., Parfum (Fragrance), Aqua (Water), Cinnamal, Coumarin, Eugenol, Benzyl Benzoate.',
    longevity: '10 – 12 hours',
    sillage: 'Moderate to strong',
    variants: sizes(10200, 15500, 23900),
    bottle: { shape: 'round', liquid: '#B97A3E', cap: 'black', glass: 'clear' },
    discountPercent: 15,
  },
  {
    name: 'The Signature Trio',
    slug: 'the-signature-trio',
    tagline: 'Éclat · Essence · Noir — 3 × 10 ml',
    gender: 'unisex',
    cats: ['gift-sets', 'signature'],
    fragranceFamily: 'Discovery Set',
    concentration: 'Eau de Parfum',
    description: 'The three founding signatures of the house in travel-size flacons, presented in an ivory coffret with a gold foil monogram. A beautiful introduction — or a gift to be remembered.',
    notes: { top: ['Bergamot', 'Lychee', 'Cardamom'], heart: ['Jasmine', 'Damask Rose', 'Oud'], base: ['White Musk', 'Vanilla', 'Sandalwood'] },
    ingredients: 'See individual fragrances. Alcohol Denat., Parfum (Fragrance), Aqua (Water).',
    longevity: '8 – 12 hours',
    sillage: 'Varies',
    variants: [{ size: '3 × 10 ml', price: 12500, stock: 30 }],
    bottle: { shape: 'classic', liquid: '#E3C897', cap: 'gold', glass: 'clear' },
    bestseller: true,
  },
  {
    name: 'Coffret Découverte',
    slug: 'coffret-decouverte',
    tagline: 'Six fragrances — 6 × 2 ml',
    gender: 'unisex',
    cats: ['gift-sets'],
    fragranceFamily: 'Discovery Set',
    description: 'Six miniature vials to discover the house at leisure. Includes a voucher for the value of the coffret, redeemable against any full-size bottle.',
    notes: { top: ['Neroli', 'Grapefruit', 'Mandarin'], heart: ['Iris', 'Tuberose', 'Rose'], base: ['Amber', 'Cedar', 'Musk'] },
    ingredients: 'See individual fragrances. Alcohol Denat., Parfum (Fragrance), Aqua (Water).',
    longevity: 'Varies',
    sillage: 'Varies',
    variants: [{ size: '6 × 2 ml', price: 4500, stock: 45 }],
    bottle: { shape: 'tall', liquid: '#E6D3A8', cap: 'ivory', glass: 'clear' },
    isNewArrival: true,
  },
];

products.forEach((p) => {
  p.images = img(p.slug);
});

const coupons = [
  { code: 'WELCOME10', description: '10% off your first order', type: 'percent', value: 10, minOrder: 0, maxDiscount: 5000 },
  { code: 'SIGNATURE15', description: '15% off orders over PKR 25,000', type: 'percent', value: 15, minOrder: 25000 },
  { code: 'GIFT1000', description: 'PKR 1,000 off orders over PKR 10,000', type: 'fixed', value: 1000, minOrder: 10000 },
];

module.exports = { categories, products, coupons };
